services:
  - type: web
    name: book-search-engine
    env: node
    region: oregon
    buildCommand: cd server && npm install --legacy-peer-deps && cd ../client && npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
